const currencyFormatter = new Intl.NumberFormat('es-CL', {
  style: 'currency',
  currency: 'CLP',
});

export const levelDefs = {
  categoria: {
    0: {
      dimensions: ["detalle_factura.categoria", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Categoría", field: "detalle_factura.categoria", valueGetter: p => p.data ? p.data["detalle_factura.categoria"] : '', enableRowGroup: true, filter: 'agSetColumnFilter' },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Valor Neto", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo Estandar", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Descuento Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Descuento Promo Venta", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Factor Conversion", field: "detalle_factura.factor_conversion_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.factor_conversion_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso Neto", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU/Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen (%)", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.categoria",
    },
    1: {
      dimensions: ["detalle_factura.nombre_producto"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
      ],
      columnDefs: [
        { headerName: "Nombre de Producto", field: "detalle_factura.nombre_producto", valueGetter: p => p.data ? p.data["detalle_factura.nombre_producto"] : '', enableRowGroup: true, filter: 'agSetColumnFilter' },
        { headerName: "Valor Neto", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo Estandar", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Descuento Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Descuento Promo Venta", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Factor Conversion", field: "detalle_factura.factor_conversion_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.factor_conversion_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso Neto", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
      ],
      drillDownField: "detalle_factura.nombre_producto",
    },
  },
  cliente: {
    0: {
      dimensions: ["detalle_factura.nombre_cliente"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
      ],
      columnDefs: [
        { headerName: "Cliente", field: "detalle_factura.nombre_cliente", valueGetter: p => p.data ? p.data["detalle_factura.nombre_cliente"] : '', enableRowGroup: true, filter: 'agSetColumnFilter' },
        { headerName: "Valor Neto", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo Estandar", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Descuento Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Descuento Promo Venta", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Factor Conversion", field: "detalle_factura.factor_conversion_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.factor_conversion_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso Neto", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.nombre_cliente",
    },
    1: {
      dimensions: ["detalle_factura.nombre_producto"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum"],
      columnDefs: [
        { headerName: "Nombre de Producto", field: "detalle_factura.nombre_producto", valueGetter: p => p.data ? p.data["detalle_factura.nombre_producto"] : '', enableRowGroup: true, filter: 'agSetColumnFilter' },
        { headerName: "Valor Neto", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo Estandar", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
      ],
    },
  },
};