const currencyFormatter = new Intl.NumberFormat('es-CL', {
  style: 'currency',
  currency: 'CLP',
});

export const levelDefs = {
  categoria: {
    0: {
      dimensions: ["detalle_factura.categoria", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Categoría", field: "detalle_factura.categoria", valueGetter: p => p.data ? p.data["detalle_factura.categoria"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.categoria",
    },
    1: {
      dimensions: ["detalle_factura.nombre_producto"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
      ],
      columnDefs: [
        { headerName: "Producto", field: "detalle_factura.nombre_producto", valueGetter: p => p.data ? p.data["detalle_factura.nombre_producto"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
      ],
      drillDownField: "detalle_factura.nombre_producto",
    },
  },
  cliente: {
    0: {
      dimensions: ["detalle_factura.nombre_cliente"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
      ],
      columnDefs: [
        { headerName: "Cliente", field: "detalle_factura.nombre_cliente", valueGetter: p => p.data ? p.data["detalle_factura.nombre_cliente"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.nombre_cliente",
    },
    1: {
      dimensions: ["detalle_factura.nombre_producto"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum"],
      columnDefs: [
        { headerName: "Producto", field: "detalle_factura.nombre_producto", valueGetter: p => p.data ? p.data["detalle_factura.nombre_producto"] : '', enableRowGroup: true, filter: 'agSetColumnFilter' },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo Estandar", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
      ],
    },
  },

  vendedor: {
    0: {
      dimensions: ["detalle_factura.vendedor", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Vendedor", field: "detalle_factura.categoria", valueGetter: p => p.data ? p.data["detalle_factura.vendedor"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.vendedor",
    },
  },
  canal: {
    0: {
      dimensions: ["detalle_factura.canal", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Canal", field: "detalle_factura.categoria", valueGetter: p => p.data ? p.data["detalle_factura.canal"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.canal",
    },
  },
  zona: {
    0: {
      dimensions: ["detalle_factura.zona_ventas", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Zona", field: "detalle_factura.zona_ventas", valueGetter: p => p.data ? p.data["detalle_factura.zona_ventas"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.zona_ventas",
    },
  },
  marca: {
    0: {
      dimensions: ["detalle_factura.marca", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Marca", field: "detalle_factura.marca", valueGetter: p => p.data ? p.data["detalle_factura.marca"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.marca",
    },
  },
  centro: {
    0: {
      dimensions: ["detalle_factura.centro", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Centro", field: "detalle_factura.centro", valueGetter: p => p.data ? p.data["detalle_factura.centro"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.centro",
    },
  },
  numero_factura: {
    0: {
      dimensions: ["detalle_factura.numero_factura", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Factura", field: "detalle_factura.numero_factura", valueGetter: p => p.data ? p.data["detalle_factura.numero_factura"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.numero_factura",
    },
  },
  familia: {
    0: {
      dimensions: ["detalle_factura.familia", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Familia", field: "detalle_factura.familia", valueGetter: p => p.data ? p.data["detalle_factura.familia"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.familia",
    },
  },
  jefe_categoria: {
    0: {
      dimensions: ["detalle_factura.jefe_categoria", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Jefe Categoria", field: "detalle_factura.jefe_categoria", valueGetter: p => p.data ? p.data["detalle_factura.jefe_categoria"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.jefe_categoria",
    },
  },
  region: {
    0: {
      dimensions: ["detalle_factura.region", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Región", field: "detalle_factura.region", valueGetter: p => p.data ? p.data["detalle_factura.region"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.region",
    },
  },
  origen: {
    0: {
      dimensions: ["detalle_factura.origen_pedido", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Orígen", field: "detalle_factura.origen_pedido", valueGetter: p => p.data ? p.data["detalle_factura.origen_pedido"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.origen_pedido",
    },
  },
  sociedad: {
    0: {
      dimensions: ["detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.sociedad",
    },
  },
  um_venta: {
    0: {
      dimensions: ["detalle_factura.um_venta", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Unidad Medida Venta", field: "detalle_factura.um_venta", valueGetter: p => p.data ? p.data["detalle_factura.um_venta"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.um_venta",
    },
  },
  direccion: {
    0: {
      dimensions: ["detalle_factura.id_sala", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Dirección", field: "detalle_factura.id_sala", valueGetter: p => p.data ? p.data["detalle_factura.id_sala"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.id_sala",
    },
  },
  especialidad: {
    0: {
      dimensions: ["detalle_factura.grupo_cliente", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Especialidad", field: "detalle_factura.grupo_cliente", valueGetter: p => p.data ? p.data["detalle_factura.grupo_cliente"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.grupo_cliente",
    },
  },
  gerencia: {
    0: {
      dimensions: ["detalle_factura.zona_ventas", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Gerencia", field: "detalle_factura.zona_ventas", valueGetter: p => p.data ? p.data["detalle_factura.zona_ventas"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.zona_ventas",
    },
  },
  sucursal: {
    0: {
      dimensions: ["detalle_factura.oficina_ventas", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Sucursal", field: "detalle_factura.oficina_ventas", valueGetter: p => p.data ? p.data["detalle_factura.oficina_ventas"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.oficina_ventas",
    },
  },
  holding: {
    0: {
      dimensions: ["detalle_factura.nombre_holding", "detalle_factura.sociedad"],
      measures: ["detalle_factura.valor_neto_sum", "detalle_factura.costo_estandar_sum",
        "detalle_factura.dcto_ajuste_sum",
        "detalle_factura.dcto_promo_venta_sum",
        "detalle_factura.factor_conversion_sum",
        "detalle_factura.peso_neto_sum",
        "detalle_factura.cliente_count",
        "detalle_factura.sku_count",
        "detalle_factura.ratio_sku_cliente",
        "detalle_factura.margen_valor",
        "detalle_factura.margen_porcentaje"
      ],
      columnDefs: [
        { headerName: "Holding", field: "detalle_factura.nombre_holding", valueGetter: p => p.data ? p.data["detalle_factura.nombre_holding"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', minWidth: 270 },
        { headerName: "Sociedad", field: "detalle_factura.sociedad", valueGetter: p => p.data ? p.data["detalle_factura.sociedad"] : '', enableRowGroup: true, filter: 'agSetColumnFilter', hide: true },
        { headerName: "Venta", field: "detalle_factura.valor_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.valor_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), sort: 'desc', filter: 'agNumberColumnFilter' },
        { headerName: "Costo", field: "detalle_factura.costo_estandar_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.costo_estandar_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto. Ajuste", field: "detalle_factura.dcto_ajuste_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_ajuste_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Dcto Promo", field: "detalle_factura.dcto_promo_venta_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.dcto_promo_venta_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Peso", field: "detalle_factura.peso_neto_sum", valueGetter: p => p.data ? Number(p.data["detalle_factura.peso_neto_sum"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} kg`, filter: 'agNumberColumnFilter' },
        { headerName: "ID Cliente", field: "detalle_factura.id_cliente", valueGetter: p => p.data ? p.data["detalle_factura.id_cliente"] : '', enableRowGroup: true, hide: true, isDynamic: true, dimension: "detalle_factura.id_cliente", filter: 'agSetColumnFilter' },
        { headerName: "Clientes", field: "detalle_factura.cliente_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.cliente_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKUs", field: "detalle_factura.sku_count", valueGetter: p => p.data ? Number(p.data["detalle_factura.sku_count"]) : 0, aggFunc: 'sum', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "SKU / Cliente", field: "detalle_factura.ratio_sku_cliente", valueGetter: p => p.data ? Number(p.data["detalle_factura.ratio_sku_cliente"]) : 0, aggFunc: 'avg', enableValue: true, filter: 'agNumberColumnFilter' },
        { headerName: "Margen $", field: "detalle_factura.margen_valor", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_valor"]) : 0, aggFunc: 'sum', enableValue: true, valueFormatter: p => currencyFormatter.format(p.value), filter: 'agNumberColumnFilter' },
        { headerName: "Margen %", field: "detalle_factura.margen_porcentaje", valueGetter: p => p.data ? Number(p.data["detalle_factura.margen_porcentaje"]) : 0, aggFunc: 'avg', enableValue: true, valueFormatter: p => `${Number(p.value).toFixed(2)} %`, filter: 'agNumberColumnFilter' },
      ],
      drillDownField: "detalle_factura.nombre_holding",
    },
  },
};